# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: "immune_repertoires_mysql"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3308:3306
    volumes:
      - immune_repertoires_database_data:/var/lib/mysql
      - /data/databases/IEDB/iedb_public.sql:/docker-entrypoint-initdb.d/iedb_public.sql 
    environment:
      - MYSQL_DATABASE=iedb_public
      - MYSQL_ROOT_PASSWORD=iedb
    networks:
      - iedb

  adminer:
    image: adminer
    container_name: "immune_repertoires_adminer"
    restart: always
    depends_on:
      - "db"
    ports:
      - 8082:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=nette
    networks:
      - iedb

networks:
    iedb:
        name: "iedb"
        external: true

volumes:
    immune_repertoires_database_data:
